apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: default
  labels:
    app: busybox-pod
spec:
  containers:
  - name: busybox-pod-cnt
    image: docker.io/library/busybox
    command: ["sleep","60"]
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    env:
    - name: TEST
      value: deneme
    ports:
    - containerPort: 80
      name:  http
  restartPolicy: Always