apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
    abc: xyz
spec:
  containers:
    - name: nginx-pod-cnt
      image: docker.io/library/nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http
  restartPolicy: Always
  