apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
        abc: xyz
    spec:
      containers:
        - name: nginx-pod-cnt
          image: docker.io/library/nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
      restartPolicy: Always
      